---
global:
  pattern: emerging-disease-detection
  hubClusterDomain: "AUTO" # this is for test only This value is automatically fetched when Invoking against a cluster

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub
  gitOpsSpec:
    operatorChannel: gitops-1.9