---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: fhir-psql-db
  namespace: {{.Values.namespace}}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: fhir-psql-db
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.fhirpsqldbsecret.key }}